# Setup
title:               Tyron Lardy
tagline:             'MSc Mathematics'
description:         'I am a PhD student at the <a href="https://www.universiteitleiden.nl/en/science/mathematics" target="_blank">Mathematical Institute</a> of Leiden University, supervised by <a href="http://www.grunwald.nl" target="_blank">Peter Gr√ºnwald</a>. This website provides information about my research as well as updates regarding the statistics group meetings at Leiden University.'
url:                 https://tlardy.github.io
baseurl:             ''
paginate:            5
permalink:           pretty
future:              true

# About/contact
author:
  name:              Tyron Lardy
  #nurl:               https://twitter.com/mdo
  email:             t.d.lardy@math.leidenuniv.nl

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
# google_analytics_id: #UA-XXXX-Y
